Stop for now to report to Okta
Cannot figure out what I am doing wrong here, but it seems I need to provide an
acsURL and entityId for a preconfigured AWS SAML app even though I do not want
to and should not have to. As it stands I get this error.

```sh
Error: failed to create SAML application:
the API returned an error:
Operation on application settings failed..
Causes:
error
Summary: acsURL: The field cannot be left blank,
error
Summary: entityID: The field cannot be left blank
```